env:
  node: true
  es6: true
parserOptions:
  ecmaVersion: 2017
extends: 'eslint:recommended'
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - always
  strict:
    - error
    - safe
  space-infix-ops:
    - error
  spaced-comment:
    - error
    - always
  no-multi-spaces:
    - error
    - ignoreEOLComments: true
      exceptions:
        Property: true
        VariableDeclarator: true