language: node_js
node_js:
  - node
  - stable
  - 12
  - 10
script:
  - npm run lint
  - npm run snyk_test
  - npm test
  - npm run check_coverage
after_success:
  - npm run upload_coverage
  - npm run snyk_monitor
